name: pull-request

on: [pull_request]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js - ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn

      # TODO: enable once all lint issues are fixed
      #- name: Lint Code
      #  run: yarn ci:lint

      - name: Build Code
        run: yarn ci:test:build

      - name: Test Package - Components/Core
        run: yarn ci:test:core:components

      - name: Test Package - Frontend
        run: yarn ci:test:frontend

      - name: Deploy Storybook
        run: yarn storybook:deploy-wallet
